### ISSUE TITLE
Should ft_colors() return a named character vector when not empty?

### ISSUE THREAD

**Issue by jameslairdsmith** [Financial-Times/ftplottools#3]
I understand the thinking that if `ft_colors()` is run without any arguments, it should return a named character vector so people can see the the colours available. And I understand that most people will make use of the `scale_*_ft()` functions for applying them directly. But if people want to pick out colours by name, I think `ft_colors()` should return an unnamed character vector.

My rationale is this: when picking colours manually, it is useful to put the function inside a `ggplot` call like so:

``` r
library(ggplot2)
library(ftplottools)

ggplot(mpg, aes(class)) +
  geom_bar(aes(fill = drv)) +
  scale_fill_manual(values = ft_colors("claret", "oxford", "teal"))
```

![](https://i.imgur.com/MwFsrW7.png)

<sup>Created on 2019-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But this returns an empty plot, because the names in the character vector are getting in the way of `ggplot` reading the values. I end up having to do this:

``` r
library(ggplot2)
library(ftplottools)

ggplot(mpg, aes(class)) +
  geom_bar(aes(fill = drv)) +
  scale_fill_manual(values = unname(ft_colors("claret", "oxford", "teal")))
```

![](https://i.imgur.com/NxmBv31.png)

<sup>Created on 2019-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think that if ft_colors() is called without arguments, it should return the named character vector. But if people are picking out colours by name, they probably don't need them repeated in the labels. This means the above is the more frequent use case where the labels are getting in the way.

If people agree, I'm happy to implement the change and put in a pull request.

**Comment by oliverelliott-ft** [comment]
Ha, I ran into this problem this morning!
I like that  by running ft_colors() you can see all the names of the colours, because I forget them all the time

So yes agree. If people are picking colours, they already know what they need, so it's ok to remove the array names
