### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by jameslairdsmith** [Financial-Times/ftplottools#7]
I have a few recommendations for how the various components are spaced in the plots. At the moment, this is our current setup:

``` r
library(ggplot2)
library(ftplottools)

mtcars %>%
  ggplot(aes(x = mpg, y = wt, colour = cyl)) + 
  geom_point() +
  ft_theme(legend_right = T) +
  labs(title = "My title",
       subtitle =  "My subtitle",
       caption = "This is a long chart caption.",
       colour = "My legend",
       x = "This is a long x-axis label",
       y = "This is a long y-axis label")
```

![](https://i.imgur.com/II48jDR.png)

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

My recommendations are the following:

1. The subtitle needs a bottom margin added. At the moment the points in the above plot are almost touching the subtitle.
2. The caption needs a top margin. At the moment is is almost touching the x-axis title.
3. Reduce the axis tick length. At the moment, they look very large to me, to the point where they are distracting. I recommend changing them to half a character in length rather than the full character length they are at the moment.
4. There is currently a lot of whitespace between the y-axis labels and the gridlines. I think that should be reduced.

If all of these changes are made, the plot ends up looking like this:

``` r
library(ggplot2)
library(ftplottools)

half_line <- 6

mtcars %>%
  ggplot(aes(x = mpg, y = wt, colour = cyl)) + 
  geom_point() +
  ft_theme(legend_right = T) +
  labs(title = "My title",
       subtitle =  "My subtitle",
       caption = "This is a long chart caption.",
       colour = "My legend",
       x = "This is a long x-axis label",
       y = "This is a long y-axis label") +
  theme(
    plot.title = element_text(margin = ggplot2::margin(b = half_line)),
    plot.subtitle = element_text(margin = ggplot2::margin(b = half_line)),
    plot.caption = element_text(margin = margin(t = half_line)),
    axis.ticks.length = ggplot2::unit(0.5,"char"),
    axis.text.y = element_text(margin = margin(r = -0.8 * half_line / 2), hjust = 1),
  )
```

![](https://i.imgur.com/OXeTFcA.png)

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I will put together a pull request with these changes. If anybody has any other recommendations, I'm happy to test them out and add them in where appropriate.

**Comment by oliverelliott-ft** [comment]
This looks good to me. Got a PR to look at?
